templateextend/extendtest/urls.py
from django.conf.urls import url
from . import views
app_name = 'extendtest'
urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^index/$', views.index, name='index')
]

templateextend/templateextend/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
urlpatterns = [
    path('admin/', admin.site.urls),
    url('extendtest/',include('extendtest.urls', namespace='extendtest') )
]

templateextend/extendtest/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=50)

templateextend/extendtest/forms.py
from django import forms
from .models import User


# class AddFom(forms.Form):
#     a = forms.IntegerField()
#     b = forms.IntegerField()

class AddFom(forms.ModelForm):
    class Meta():
        model = User
        fields = ['username', 'password']

templateextend/extendtest/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponseRedirect, response, HttpResponse
from .forms import  AddFom
# Create your views here.

def login(request):
    if request.method == 'GET':
        form = AddFom()
        return render(request, 'extendtest/login.html', {'form': form})
    elif request.method == "POST":
        form = AddFom(request.POST)
        if form.is_valid():
            form.save()
            # a = form.cleaned_data['a']
            # b = form.cleaned_data['b']
            # return HttpResponse(str(int(a))+str(int(b)))
            return HttpResponse('登录成功')
    # return render(request, 'extendtest/login.html')

def index(request):
    uname = request.POST['uname']
    return render(request, 'extendtest/index.html', {'uname':uname})

templateextend/templates/extendtest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {{ uname }}
</body>
</html>

templateextend/templates/extendtest/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
    <h1>登录</h1>
    <form action="{% url 'extendtest:login' %}" method="post">
        {% csrf_token %}
        {{ form.username }}
        <br>
        {{ form.password }}
        <br>
    {#    <input type="text" name="uname" >#}
        <input type="submit" value="注册">
    </form>
</body>
</html>