demo1/booktest/urls.py
from django.conf.urls import url
from . import views

app_name = 'booktest'

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),

    url(r'^list/$', views.list, name='list'),
    url(r'^detail/(\d+)/$', views.detail, name='detail'),
    url(r'^delete/(\d+)/$',views.delete, name='delete'),
    url(r'^addhero/(\d+)/$', views.addhero, name='addhero'),
    url(r'^addherohandler/$', views.addherohandler, name='addherohandler'),
    url(r'^area/$', views.area, name='area')
]

demo1/demo1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('booktest/', include('booktest.urls', namespace='booktest'))
]


"""
 项目URL
 通过urlpatterns 列表中的内容将路由和视图绑定
"""

demo1/booktest/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Bookinfo(models.Model):
    btitle = models.CharField(max_length=20)
    bpub_data = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.btitle


class HeroInfo(models.Model):
    hname = models.CharField(max_length=20)
    hgender = models.BooleanField()
    hcontent = models.CharField(max_length=50)
    # 外键 第一个参数为表名 第二个参数代表类型
    hbook = models.ForeignKey('BookInfo', on_delete=models.CASCADE)
    def __str__(self):
        return self.hname

    def skill(self):
        return self.hcontent
    skill.short_description = '武功'

    def sex(self):
        return self.hgender
    sex.short_description = '性别'

    def name(self):
        return self.hname
    name.short_description = '主角'

    def book(self):
        return self.hbook
    book.short_description = '小说'

class AreaInfo(models.Model):
    atitle = models.CharField(max_length=20)
    aparent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
    def __str__(self):
        return self.atitle

class MyUser(User):
    url = models.URLField(blank=True, null=True, default='http://www.baidu.com')






"""
 django MVT  M
 ORM 对象中O
 需要定义实体类
"""

demo1/booktest/forms.py
from django import forms

demo1/booktest/views.py
from django.shortcuts import render,redirect, reverse, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Bookinfo,HeroInfo, AreaInfo,MyUser
from django.contrib.auth import authenticate, login as lgi, logout as lgo
from .util import checklogin
from django.template import loader
import datetime
# Create your views here.

# 定义视图函数
# @checklogin
def index(request):
    # return HttpResponse('首页')
    # 加载模板
    # indextem = loader.get_template('booktest/index.html')
    # # 使用变量渲染模板
    # con = {'username':'yang teng'}
    # result = indextem.render(con)
    # # 返回模板
    # return HttpResponse(result)
    # 快捷方式
    # res = request.COOKIES.get('username')

    # 登录功能
    # username = request.session.get('username')
    # is_ok = request.user.is_authenticated
    # print(username, is_ok, locals())
    return render(request,'booktest/index.html', locals())

    # HttpResponse 对象
    # response = HttpResponse()
    # if 'h1' in request.COOKIES.keys():
    #     response.write('<h1>一级标题<h1>')
    # response.set_cookie('h1', 500)
    # return response


def login(request):
    if request.method == 'GET':
        return render(request,'booktest/login.html')
    # elif request.method == 'POST':
    #     username = request.POST['username']
    #     request.session['username'] = username
    #     return redirect(reverse('booktest:index'))
    else:
        username = request.POST.get('username')
        pwd = request.POST.get('password')

        user = authenticate(request, username=username, password=pwd )
        if user:
            # request.session['username'] = username
            lgi(request, user)
            return redirect(reverse('booktest:index'))
        else:
            return render(request, 'booktest/login.html', {"error": "用户名或者密码错误"})


def register(request):
    if request.method == 'POST':
        username = request.POST.get('account')
        pwd = request.POST.get('confirm')
        pwd2 = request.POST.get('confirm2')
        error = None
        try:
            error = '用户已存在'
            if MyUser.objects.filter(username=username):
                return render(request, 'booktest/login.html', {'error': error})
        except:
            if pwd != pwd2:
                error = '密码不一致'
                return render(request, 'booktest/login.html', {'error':error})
            else:
                MyUser.objects.create_user(username=username, password=pwd, url='http://yang.com')
                return redirect(reverse('booktest:login'))




def logout(request):
    res = redirect(reverse('booktest:index'))
    lgo(request)
    return res



def list(request):

    book = Bookinfo.objects.all()
    res = render(request,'booktest/list.html',{'booklist':book})
    # res.set_cookie('username','yang',expires=datetime.datetime.now()+datetime.timedelta(days=10))
    return res

def detail(request,id):
    # try:
    #     # book = Bookinfo.objects.get(pk=int(id))
    #     # book = Bookinfo.objects.all()[int(id)].btitle
    #     # return HttpResponse(book)
    # except:
    #     return HttpResponse('错误id')
    book = Bookinfo.objects.get(pk=int(id))
    return render(request, 'booktest/detail.html', {'booklist':book})

def delete(request,id):
    # Bookinfo.objects.get(pk=id).delete()
    b1 = get_object_or_404(Bookinfo, pk=id)
    b1.delete()
    b1.BookInfo.objects.all()
    # return render(request, 'booktest/list.html', {'booklist': b1})
    # 重定向，刷新当前页面
    return HttpResponseRedirect('/booktest/list', {'booklist':b1})
    # return redirect(reverse('booktest:list'))

def addhero(request, id):
    return render(request,'booktest/addhero.html', {'bookid': id})
    # return HttpResponse("添加成功")

def addherohandler(request):
    name = request.POST['name']
    gender = request.POST['sex']
    content = request.POST['content']
    bookid = request.POST['bookid']
    print(name,gender,content,bookid)
    book = Bookinfo.objects.get(pk=bookid)
    hero = HeroInfo()
    hero.hname = name
    hero.hgender = gender
    hero.hcontent = content
    hero.hbook = book
    hero.save()
    return HttpResponseRedirect('/booktest/detail/'+str(bookid)+'/', {'booklist':book})

def area(request):
    area = AreaInfo.objects.get(pk=3)
    return render(request, 'booktest/area.html', {'area':area})




"""
 视图函数
 将函数和路由绑定
"""

demo1/templates/booktest/addhero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加英雄</title>
</head>
<body>
    <form action="{% url 'booktest:addherohandler' %}" method="post">
    	姓名: <input type="text" name='name' autocomplete="off"><br>
        性别: 男 <input type="radio" value="1" name="sex" checked> 女 <input type="radio" value="0" name="sex" checked>
        武功:<input type="text" name="content" autocomplete="off"><br>
        <input type="hidden" value="{{ bookid }}" name="bookid">
		<input type="submit" value="添加">
    </form>
</body>
</html>

demo1/templates/booktest/area.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>地区</title>
</head>
<body>
    当前地区：{{ area.atitle }}
    <br>
    上级地区：{{ area.aparent }}
    <br>
    下级地区：
    <ul>
        {% for a in area.areainfo_set.all %}
        <li>{{ a.atitle }}</li>
        {% endfor %}
    </ul>
</body>
</html>

demo1/templates/booktest/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>书籍内容</title>
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <div class="container">
    <h2>书名: {{ booklist.btitle }}</h2>
    <ul>
        {% for hero in booklist.heroinfo_set.all %}
            <li>{{ hero.hname}}---{{ hero.hcontent }}</li>

        {% empty %}
            <h3>没有内容</h3>
        {% endfor %}
    </ul>
    <a href="{% url 'booktest:addhero' booklist.id %}">添加角色</a>
    <a href="{% url 'booktest:list' %}">返回上一页</a>
    </div>
</body>
</html>

demo1/templates/booktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    {% load static from staticfiles %}
{#    <link rel="stylesheet" href="/static/css/main.css">#}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>

    <div class="container">
        {% if request.user.username  %}
            <h2>{{ user.username }}</h2>
{#          <a href="/booktest/list/">列表页</a>#}
            <a href="{% url 'booktest:list' %}">列表页</a>
            <br>
            <a href="{% url 'booktest:logout' %}">退出登录</a>
            <br>
        {% else %}
            <a href="{% url 'booktest:login' %}">登录</a>
            <br>
        {% endif %}

    </div>
    {#        <img src="/static/img/1.png" alt="没有图片">#}
     <img src="{% static 'img/1.png' %}" class="img1" alt="图片正在加载">

</body>
</html>

demo1/templates/booktest/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>列表页</title>
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <div class="container">
    <h1>书籍信息</h1>
    <ul>
        {% for book in booklist  %}
{#            <li><a href="/booktest/detail/{{ book.id }}">{{ book.btitle }}</a></li>#}
            <li><a href="{%url 'booktest:detail' book.id%}">{{ book.btitle }}</a>
                <a href="{% url 'booktest:delete' book.id %}">删除</a>

            </li>
        {% empty %}
            <h3>没有书籍</h3>
        {% endfor %}

    </ul>
{#    <a href="{% url 'booktest:addhero' %}">添加书籍</a>#}
    <a href="{% url 'booktest:index' %}">返回首页</a>
    </div>

</body>
</html>

demo1/templates/booktest/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>

</head>
<body>
{#<form action="{% url 'booktest:login' %}" method="post">#}
{#    用户名: <input type="text" name="username">#}
{#    <br>#}
{#    <input type="submit" value="登录">#}
{#</form>#}
{#<br><br><br><br>#}
<div class="container">
    <!-- Nav tabs -->
  <h1>bootstrap登录注册</h1>
  <h2>{{ error }}</h2>
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#login" aria-controls="login" role="tab" data-toggle="tab">login</a></li>
    <li role="presentation"><a href="#register" aria-controls="register" role="tab" data-toggle="tab">register</a></li>

  </ul>
  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="login">
        <h2>登录</h2>
        <form class="form-horizontal" action="{% url 'booktest:login' %}" method="post">
            {% csrf_token %}
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">用户名</label>
            <div class="col-sm-10">
              <input type="text" name="username" class="form-control" id="username" placeholder="请输入用户名">
            </div>
          </div>
          <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">密码</label>
            <div class="col-sm-10">
              <input type="password" name="password" class="form-control" id="password" placeholder="请输入密码">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-default">登录</button>
            </div>
          </div>
        </form>
    </div>
    <div role="tabpanel" class="tab-pane" id="register">
        <h2>注册</h2>
        <form class="form-horizontal" action="{% url 'booktest:register' %}" method="post">
            {% csrf_token %}
          <div class="form-group">
            <label for="account" class="col-sm-2 control-label">用户名</label>
            <div class="col-sm-10">
              <input type="text" name="account" class="form-control" id="account" placeholder="请输入注册用户">
            </div>
          </div>
          <div class="form-group">
            <label for="confirm" class="col-sm-2 control-label">密码</label>
            <div class="col-sm-10">
              <input type="password" name="confirm" class="form-control" id="confirm" placeholder="请输入注册密码">
            </div>
          </div>
            <div class="form-group">
            <label for="confirm" class="col-sm-2 control-label">重复密码</label>
            <div class="col-sm-10">
              <input type="password" name="confirm2" class="form-control" id="confirm2" placeholder="请输入重复密码">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-default">注册</button>
            </div>
          </div>
        </form>
    </div>
  </div>

</div>


</body>
</html>

demo1/templates/booktest/登录.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
	</head>
	<body>
		<form action="http://127.0.0.1:8000/extendtest/index/" method="post">
			<input type="text" name="uname" />
			<input type="submit" value="登录" />
		</form>
	</body>
</html>